# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wiesz @ Rozumiesz
name: Wiesz @ Rozumiesz - blog o tym, że uczyć możesz się przez całe życie.
email: mi.siedlecki@gmail.com
copyright: 2017&mdash;2020
description: > # this means to ignore newlines until "baseurl:"
  Nowa wiedza każdego dnia!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://siedlmi.github.io" # the base hostname & protocol for your site
twitter_username: wieszrozumiesz
github_username:  siedlmi

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
paginate: 5
paginate_path: "/blog/page:num/"

# Where things are
collections:
  my_categories:
    output: true
    permalink: /category/:name/
  my_tags:
    output: true
    permalink: /tag/:name/

efaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag
  -
    scope:
      path: "project"
    values:
      layout: project
